export const ROUTE = {
    LAYOUT: '/',
    HOME: '/',
    LOGIN: '/login',
    REGISTER : '/register',
    LOGOUT: '/logout',
    PROFILE: '/profile',
    GENERAL: '/profile/general',
    CHANGE_PROFILE: '/profile/change-profile',
    HISTORY: '/profile/history',
    MOVIE_NOW_SHOWING: '/movies/now-showing',
    MOVIE_COMING_SOON: '/movies/coming-soon',
    MOVIE_DETAIL: '/movie/:title',
    TICKET: '/ticket',
    AUTH_PAYMENT: '/payment',
    PAYMENT_MOMO: '/payment/momo',
    NO_CART: '/nocart',
    CINEMA: '/cinema',
}
